[package]
name = "tictactoe"
version = "0.1.0"
authors = ["doraneko94 <shuntaro94@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13"
rand = "0.7"
tch = "0.1.7"
anyhow = "1.0.31"
